### ISSUE TITLE
My program has been blocked by server

### ISSUE THREAD

**Issue by HONGBAEKIM** [HONGBAEKIM/hongbooking#17]
My program has been blocked by server

**Comment by HongbaeKim** [comment]
1.Added undetected_chromedriver
 import undetected_chromedriver as uc 
 options = uc.ChromeOptions()
 #options.add_argument("--headless")
 driver = uc.Chrome(options=options)



2. or Added stealth 

from selenium_stealth import stealth
options = webdriver.ChromeOptions()
options.add_argument("--headless")
driver = webdriver.Chrome(options=options)

stealth(driver,
        languages=["en-US", "en"],
        vendor="Google Inc.",
        platform="Win32",
        webgl_vendor="Intel Inc.",
        renderer="Intel Iris OpenGL Engine",
        fix_hairline=True,
)


and driver.quit() instead of driver.close()

**Comment by HongbaeKim** [comment]
1.Added undetected_chromedriver
import undetected_chromedriver as uc
options = uc.ChromeOptions()
#options.add_argument("--headless")
driver = uc.Chrome(options=options)

and solved
